proc global RandGenerator(int $dupeNum, float $xMin, float $yMin, float $zMin, float $xMax, float $yMax, float $zMax,)
{
    string $selected[] = `ls -sl`;

    if size($selected[]) = 0
    {
        break;
    }

    for ($i = 0; $i < size($selected[]); $i++)
    {
        duplicate $selected[$i];

        for ($j = 0; $j < $dupeNum; $j++)
        {
            float $randX= `rand `
            float $randy=
            float $randZ=
        }
    }
}